### ISSUE TITLE
Comments on initial repository review

### ISSUE THREAD

**Issue by jpmjpmjpm** [jjbernard/pyhotsax#1]
**Package looks good overall!** Some comments.

- `self.discords_location` variable seems not to be used.

- `defaultdict()` are set without a `default_factory`.

- At    https://github.com/jjbernard/pyhotsax/blob/a97e0e1e3467d250e95d4323fd37b0c776b7f56b/hotsax.py#L134, shouldn't `data` be copied to avoid modifications?

**Comment by jjbernard** [comment]
Thanks @jpmjpmjpm, fixed the code!
